version: 2.1
jobs:
  unit_test:
    steps:
      - checkout
      - run: cd PrebidMobile
      - run: ./gradlew API1.0:testDebugUnitTest
  integration_test:
    steps:
      - checkout
      - run: echo "Hello World"
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - unit_test
      - integration_test