version: 2.1
jobs:
  unit_test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: PrebidMobile/gradlew API1.0:testDebugUnitTest
  integration_test:
    docker:
      - image: circleci/node:4.8.2  
    steps:
      - checkout
      - run: echo "Hello World"
workflows:
  version: 2.1
  tests:
    jobs:
      - unit_test
      - integration_test