version: 2.1
jobs:
  unit_test:
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run: cd PrebidMobile && ./gradlew API1.0:testDebugUnitTest
  integration_test:
    docker:
      - image: circleci/android:api-28-alpha 
    steps:
      - checkout
      - run: echo "Hello World"
workflows:
  version: 2.1
  tests:
    jobs:
      - unit_test
      - integration_test