version: 2.1
jobs:
  unit_test:
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run: 
          name: Run Unit Tests
          command: 
  integration_test:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: cd PrebidMobile && ./gradlew API1.0:testDebugUnitTest
workflows:
  version: 2.1
  tests:
    jobs:
      - unit_test
      - integration_test